### ISSUE TITLE
Messages with urls don't show on slack (invalid_blocks)

### ISSUE THREAD

**Issue by twouters** [Sorunome/matrix-slack-parser#4]
```
Apr 07 11:55:56 midgard node[114006]: [ERROR]  WebClient:2 must be more than 0 characters [json-pointer:/blocks/0/elements/0/elements/0/text]
Apr 07 11:55:56 midgard node[114006]: (node:114006) UnhandledPromiseRejectionWarning: Error: An API error occurred: invalid_blocks
Apr 07 11:55:56 midgard node[114006]:     at Object.platformErrorFromResult (/home/twouters/mx-puppet-slack/node_modules/@slack/web-api/dist/errors.js:50:33)
Apr 07 11:55:56 midgard node[114006]:     at WebClient.apiCall (/home/twouters/mx-puppet-slack/node_modules/@slack/web-api/dist/WebClient.js:485:28)
Apr 07 11:55:56 midgard node[114006]:     at runMicrotasks (<anonymous>)
Apr 07 11:55:56 midgard node[114006]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
Apr 07 11:55:56 midgard node[114006]: (node:114006) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 45)
```

**Comment by Sorunome** [comment]
Fixed in https://github.com/Sorunome/matrix-slack-parser/commit/5ad9aaf9122f90e97af39ce9f7c3250a46621efc
